### ISSUE TITLE
Use the JEST test to find Referenceer: ATYPOGRAPHY is not defined 

### ISSUE THREAD

**Issue by 520Girl** [bit-ocean-studio/infra#149]
**@bit-ocean/auto-import configure:**

![image](https://github.com/user-attachments/assets/f6eb9fbd-533e-4035-a83c-5a16151b4de4)
**jest use:**

![image](https://github.com/user-attachments/assets/2968d066-2952-4b17-8e2a-5d24019b57e5)
**components use:**

![image](https://github.com/user-attachments/assets/a842b209-bf22-46b8-b6e6-70961d162230)

@bit-ocean/auto-import automatically imports the antd component. Use the JEST test to find Referenceer: ATYPOGRAPHY is not defined

How to solve it? @recallwei

**Comment by recallwei** [comment]
Reference: https://github.com/recallwei/unplugin-auto-import-antd/issues/4#issuecomment-2265601706
